// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9bMAEz_dsX2DzJXzrXP6n_sLp_fs4Jyw',
    appId: '1:697299245775:web:848373c52d9bd3f3e935ba',
    messagingSenderId: '697299245775',
    projectId: 'emailauth-46527',
    authDomain: 'emailauth-46527.firebaseapp.com',
    storageBucket: 'emailauth-46527.appspot.com',
    measurementId: 'G-VKVR8X5ZWW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGQP9j1Y7rbvITBdNyI-1RSKGiDj2J7co',
    appId: '1:697299245775:android:7f494d3cf3eeb2dae935ba',
    messagingSenderId: '697299245775',
    projectId: 'emailauth-46527',
    storageBucket: 'emailauth-46527.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRUPl9y0ShsrH9Km0F7-BhvpR2WcLDkPM',
    appId: '1:697299245775:ios:78ca7f52e3e6f6e8e935ba',
    messagingSenderId: '697299245775',
    projectId: 'emailauth-46527',
    storageBucket: 'emailauth-46527.appspot.com',
    iosBundleId: 'com.example.emailAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRUPl9y0ShsrH9Km0F7-BhvpR2WcLDkPM',
    appId: '1:697299245775:ios:78ca7f52e3e6f6e8e935ba',
    messagingSenderId: '697299245775',
    projectId: 'emailauth-46527',
    storageBucket: 'emailauth-46527.appspot.com',
    iosBundleId: 'com.example.emailAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9bMAEz_dsX2DzJXzrXP6n_sLp_fs4Jyw',
    appId: '1:697299245775:web:957bb797f72de37be935ba',
    messagingSenderId: '697299245775',
    projectId: 'emailauth-46527',
    authDomain: 'emailauth-46527.firebaseapp.com',
    storageBucket: 'emailauth-46527.appspot.com',
    measurementId: 'G-HM5DBK8YFF',
  );

}